rplidar_1:
  ros__parameters:
    angle_compensate: true
    inverted: false
    frame_id: laser
    serial_baudrate: 115200
    portName: Quad RS232-HS
    active: true
rplidar_2:
  ros__parameters:
    angle_compensate: true
    inverted: false
    frame_id: laser
    serial_baudrate: 115200
    portName: Quad RS232-HS
    active: true
rplidar_3:
  ros__parameters:
    angle_compensate: true
    inverted: false
    frame_id: laser
    serial_baudrate: 115200
    portName: Quad RS232-HS
    active: true
rplidar_4:
  ros__parameters:
    angle_compensate: true
    inverted: false
    frame_id: laser
    serial_baudrate: 115200
    portName: Quad RS232-HS
    active: true